; PlatformIO Project Configuration File for PlanKO ESP32 Controller
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = gateway

[env]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
monitor_dtr = 1
monitor_rts = 0
board_build.partitions = huge_app.csv
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    links2004/WebSockets @ ^2.4.1
    bblanchon/ArduinoJson @ ^7.0.4
    h2zero/NimBLE-Arduino @ ^1.4.2

; ==============================================================================
; 1. GATEWAY (BLE Central + Wi-Fi WebSocket Server)
; ==============================================================================
[env:gateway]
upload_port = COM3
monitor_port = COM3
build_flags =
    ${env.build_flags}
    -DROLE_GATEWAY

; ==============================================================================
; 2. IMU NODES 1 - 4 (BLE Peripheral + MPU-6050 IMU Sensor)
; ==============================================================================
[env:imu_node_1]
upload_port = COM6
monitor_port = COM6
build_flags =
    ${env.build_flags}
    -DROLE_NODE
    -DNODE_ID=1

[env:imu_node_2]
build_flags =
    ${env.build_flags}
    -DROLE_NODE
    -DNODE_ID=2

[env:imu_node_3]
build_flags =
    ${env.build_flags}
    -DROLE_NODE
    -DNODE_ID=3

[env:imu_node_4]
build_flags =
    ${env.build_flags}
    -DROLE_NODE
    -DNODE_ID=4